2024-06-29 13:31:08,554 INFO    MainThread:19676 [wandb_setup.py:_flush():68] Configure stats pid to 19676
2024-06-29 13:31:08,555 INFO    MainThread:19676 [wandb_setup.py:_flush():68] Loading settings from /Users/ryanmerrithew/.config/wandb/settings
2024-06-29 13:31:08,555 INFO    MainThread:19676 [wandb_setup.py:_flush():68] Loading settings from /Users/ryanmerrithew/Project-Build-an-ML-Pipeline-Starter/src/eda/wandb/settings
2024-06-29 13:31:08,556 INFO    MainThread:19676 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2024-06-29 13:31:08,556 INFO    MainThread:19676 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-06-29 13:31:08,556 INFO    MainThread:19676 [wandb_init.py:_log_setup():478] Logging user logs to /Users/ryanmerrithew/Project-Build-an-ML-Pipeline-Starter/src/eda/wandb/run-20240629_133108-o4yig8tk/logs/debug.log
2024-06-29 13:31:08,556 INFO    MainThread:19676 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/ryanmerrithew/Project-Build-an-ML-Pipeline-Starter/src/eda/wandb/run-20240629_133108-o4yig8tk/logs/debug-internal.log
2024-06-29 13:31:08,556 INFO    MainThread:19676 [wandb_init.py:init():518] calling init triggers
2024-06-29 13:31:08,556 INFO    MainThread:19676 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2024-06-29 13:31:08,556 INFO    MainThread:19676 [wandb_init.py:init():571] starting backend
2024-06-29 13:31:08,556 INFO    MainThread:19676 [wandb_init.py:init():575] setting up manager
2024-06-29 13:31:08,571 ERROR   MainThread:19676 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/ryanmerrithew/anaconda3/envs/nyc_airbnb_dev/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/ryanmerrithew/anaconda3/envs/nyc_airbnb_dev/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 576, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/Users/ryanmerrithew/anaconda3/envs/nyc_airbnb_dev/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 174, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/Users/ryanmerrithew/anaconda3/envs/nyc_airbnb_dev/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/Users/ryanmerrithew/anaconda3/envs/nyc_airbnb_dev/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/Users/ryanmerrithew/anaconda3/envs/nyc_airbnb_dev/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/ryanmerrithew/anaconda3/envs/nyc_airbnb_dev/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/ryanmerrithew/anaconda3/envs/nyc_airbnb_dev/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
